### ISSUE TITLE
Install failed with permissions issue

### ISSUE THREAD

**Issue by jamieforrest** [RocketChat/heroku-buildpack-meteor#7]
```
Writing location.js file
Phantom installation failed { [Error: EACCES: permission denied, open '/tmp/build_8085e12283237c3b6298c6df1be96df1/RocketChat-Rocket.Chat-a9de8a4/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/tmp/build_8085e12283237c3b6298c6df1be96df1/RocketChat-Rocket.Chat-a9de8a4/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js' } Error: EACCES: permission denied, open '/tmp/build_8085e12283237c3b6298c6df1be96df1/RocketChat-Rocket.Chat-a9de8a4/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at writeLocationFile (/tmp/build_8085e12283237c3b6298c6df1be96df1/RocketChat-Rocket.Chat-a9de8a4/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/util.js:84:6)
    at Promise._successFn (/tmp/build_8085e12283237c3b6298c6df1be96df1/RocketChat-Rocket.Chat-a9de8a4/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/install.js:88:5)
    at nextTickCallback (/tmp/build_8085e12283237c3b6298c6df1be96df1/RocketChat-Rocket.Chat-a9de8a4/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/kew/kew.js:47:28)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

Possibly related to [this issue in the main repo](https://github.com/RocketChat/Rocket.Chat/issues/4866)?

**Comment by engelgabriel** [comment]
This should be all fixed now. Please try setting `BUILDPACK_CLEAR_CACHE=1` on the environment variables configuration panel if it is still a problem for you.

In case the problem persists, please reopen this issue with more info.
